name: build.yml
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.1.1'
    - name: Use cmake
      run: cmake --version
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make