name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.1.1'
    - name: Use cmake
      run: cmake --version
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libjack-jackd2-dev libpulse-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make